name: myenv
channels:
  - defaults
dependencies:
- python=3.9
- pip:
  - streamlit
  - numpy
  - pandas
  - scipy
  - requests
  - os
  - string
  - random
  - streamlit.components.v1
  - mpl_toolkits
  - subprocess
  - IPython
  - folium

  

