name: myenv
channels:
  - defaults
dependencies:
  - python=3.10
  - streamlit
  - numpy
  - pandas
  - matplotlib
  - scipy
  - requests
  - pip
  - os
  - string
  - random
  - streamlit.components.v1
  - mpl_toolkits
  - subprocess
  

