name: myenv
channels:
  - defaults
dependencies:
  - python=3.10
  - streamlit
  - streamlit.components.v1
  - numpy
  - pandas
  - mpl_toolkits.mplot3d
  - scipy
  - datetime
  - pytz
  - glob
  - os
  - string
  - random
  - subprocess
  - pythoncom
  - IPython
  - folium
  - requests
  - pip
