name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.10

    - name: Create environment
      run: conda env create -f environment.yml

    - name: Activate environment
      run: echo "conda activate myenv" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        source activate myenv
        python -m pip install --upgrade pip

    - name: Run tests
      run: |
        source activate myenv
        python -m unittest discover
